// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHsJXn_R2k4gAhvREsruxDQCB6pxIO3Gk',
    appId: '1:148021748774:web:00e7a3c950d056c90972e7',
    messagingSenderId: '148021748774',
    projectId: 'aft-arabia',
    authDomain: 'aft-arabia.firebaseapp.com',
    storageBucket: 'aft-arabia.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHw3kBg05vxQCbhMiHyvsZYAqfZ-Z2G4M',
    appId: '1:148021748774:android:6062a54511b7b73d0972e7',
    messagingSenderId: '148021748774',
    projectId: 'aft-arabia',
    storageBucket: 'aft-arabia.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa1C4tzfqD72k1XdEj52eVMEV-EaY0qRk',
    appId: '1:148021748774:ios:123df43eeddab1980972e7',
    messagingSenderId: '148021748774',
    projectId: 'aft-arabia',
    storageBucket: 'aft-arabia.appspot.com',
    iosClientId:
        '148021748774-mfucn0vmpp82q898mj0l1ce81fkaii7u.apps.googleusercontent.com',
    iosBundleId: 'com.example.coolApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa1C4tzfqD72k1XdEj52eVMEV-EaY0qRk',
    appId: '1:148021748774:ios:123df43eeddab1980972e7',
    messagingSenderId: '148021748774',
    projectId: 'aft-arabia',
    storageBucket: 'aft-arabia.appspot.com',
    iosClientId:
        '148021748774-mfucn0vmpp82q898mj0l1ce81fkaii7u.apps.googleusercontent.com',
    iosBundleId: 'com.example.coolApp',
  );
}
